In [11]:
#!pip install numpy
import numpy as np
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x = np.array(l)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.dtype

dtype('int32')

In [10]:
l2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(l2d)
arr2d = np.array(l2d)
arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2d.shape

(3, 3)

In [12]:
np.arange(0, 31, 4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [13]:
x = np.arange(60)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [12]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
x.reshape(10, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [21]:
x = x.reshape(4, 3, 5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [22]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [23]:
x.reshape(2,3,2,5)

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]],


       [[[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]])

In [18]:
x = np.zeros((10,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
y = np.ones((10,5))
y = y+3
y

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [22]:
x+y

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a = np.eye(4)*2 #identity matrix
a

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [26]:
b = np.ones((4,3))+4
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [55]:
a.dot(b)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [57]:
b = np.arange(60).reshape(10,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [58]:
b.mean()

29.5

In [59]:
b.std()

17.318102282486574

In [61]:
b.var()

299.9166666666667

In [62]:
np.mean(b)

29.5

In [69]:
b.std(axis = 1)

array([1.70782513, 1.70782513, 1.70782513, 1.70782513, 1.70782513,
       1.70782513, 1.70782513, 1.70782513, 1.70782513, 1.70782513])

In [70]:
b.var(axis = 1)

array([2.91666667, 2.91666667, 2.91666667, 2.91666667, 2.91666667,
       2.91666667, 2.91666667, 2.91666667, 2.91666667, 2.91666667])

In [71]:
b.mean(axis = 0) #row wise

array([27., 28., 29., 30., 31., 32.])

In [72]:
b.mean(axis = 1) #column wise

array([ 2.5,  8.5, 14.5, 20.5, 26.5, 32.5, 38.5, 44.5, 50.5, 56.5])

In [73]:
np.log(b)

C:\Users\Radhakrishnan P\AppData\Local\Temp\ipykernel_7264\4200754868.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
        2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872,
        2.83321334],
       [2.89037176, 2.94443898, 2.99573227, 3.04452244, 3.09104245,
        3.13549422],
       [3.17805383, 3.21887582, 3.25809654, 3.29583687, 3.33220451,
        3.36729583],
       [3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
        3.55534806],
       [3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
        3.71357207],
       [3.73766962, 3.76120012, 3.78418963, 3.80666249, 3.8286414 ,
        3.8501476 ],
       [3.87120101, 3.8918203 , 3.91202301, 3.93182563, 3.95124372,
        3.97029191],
       [3.98898405, 4.00733319, 4.02535169, 4.04305127, 4.06044301,
        4.07753744]])

In [74]:
np.log2(16)

4.0

In [81]:
np.sin(b)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
        -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332,
        -0.96139749],
       [-0.75098725,  0.14987721,  0.91294525,  0.83665564, -0.00885131,
        -0.8462204 ],
       [-0.90557836, -0.13235175,  0.76255845,  0.95637593,  0.27090579,
        -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267],
       [-0.99177885, -0.64353813,  0.29636858,  0.96379539,  0.74511316,
        -0.15862267],
       [-0.91652155, -0.83177474,  0.01770193,  0.85090352,  0.90178835,
         0.12357312],
       [-0.76825466, -0.95375265, -0.26237485,  0.67022918,  0.98662759,
         0.39592515],
       [-0.55878905, -0.99975517, -0.521551  ,  0.43616476,  0.99287265,
         0.63673801]])

In [82]:
np.sin(10)

-0.5440211108893698

In [83]:
np.radians(180)

3.141592653589793

In [84]:
np.degrees(3.141592653589793)

180.0

In [28]:
np.random.rand(10,10)

array([[0.18890527, 0.87016183, 0.83838542, 0.56938914, 0.9545177 ,
        0.48387403, 0.72641942, 0.20257068, 0.12314514, 0.78895932],
       [0.82183657, 0.6764188 , 0.00561903, 0.28228612, 0.26059709,
        0.25620995, 0.97692892, 0.73585951, 0.5905882 , 0.8955809 ],
       [0.53670138, 0.26999472, 0.43083385, 0.90939787, 0.51807536,
        0.25733605, 0.43636691, 0.85687027, 0.06832844, 0.82761803],
       [0.31426412, 0.89590692, 0.35070764, 0.80087653, 0.18676055,
        0.58641851, 0.97359638, 0.02093159, 0.27986021, 0.59238625],
       [0.2862093 , 0.96759787, 0.57614277, 0.39574619, 0.37880736,
        0.61331876, 0.69605266, 0.06289378, 0.04750853, 0.42987134],
       [0.40031607, 0.18037382, 0.90269648, 0.90051455, 0.28665621,
        0.00305212, 0.1079705 , 0.71503438, 0.60799616, 0.79628626],
       [0.81822369, 0.33757361, 0.47263435, 0.42954647, 0.62114301,
        0.62981472, 0.36183987, 0.73252154, 0.31158831, 0.49262892],
       [0.27380919, 0.46384767, 0.6109259

In [29]:
np.random.randint(10,20,(7,3))

array([[16, 11, 14],
       [11, 19, 15],
       [16, 14, 19],
       [19, 17, 15],
       [14, 13, 15],
       [11, 14, 14],
       [17, 18, 13]])

In [30]:
s = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.random.shuffle(s)
s

array([2, 0, 6, 5, 7, 8, 3, 4, 9, 1])

In [37]:
s.argmax() # returns the index of the max value in the array

8

In [38]:
s.argmin() # returns the index of the min value in the array

1

In [35]:
np.ones(4)

array([1., 1., 1., 1.])