In [2]:
#!pip  install numpy

In [3]:
import numpy as np # importing numpy module
l = [1, 2, 3, 4, 5, 6] # normal array

In [4]:
l

[1, 2, 3, 4, 5, 6]

In [5]:
x = np.array(l) # numpy array declaration

In [6]:
x

array([1, 2, 3, 4, 5, 6])

In [7]:
l2d = [[1, 2, 3],[4, 5, 6],[7, 8, 9]] #normal 2d array declaration

In [8]:
l2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr2d = np.array(l2d) # numpy 2d array

In [10]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
x = np.arange(60) # range function in numpy
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [74]:
x.reshape(10,6) # reshape is used to create dimensional arrays

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [16]:
l.reshape(2, 3) # reshape works only on numpy arrays and not on normal arrays 

AttributeError: 'list' object has no attribute 'reshape'

In [26]:
x = np.arange(60).reshape(5,2,6) # 3d array
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]])

In [51]:
y = np.arange(60).reshape(5,2,3,2) #4d array
y

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]]],


       [[[48, 49],
         [50, 51],
         [52, 53]],

        [[54, 55],
         [56, 57],
         [58, 59]]]])

In [52]:
y.dtype

dtype('int32')

In [53]:
y.shape

(5, 2, 3, 2)

In [54]:
a = np.zeros((4,4))+3
a

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [55]:
b = np.ones((4,4))*5
b

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [56]:
c = np.eye(4) # identity matrix
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
a+b

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [58]:
a.dot(c) # matrix multiplication

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [59]:
y

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]]],


       [[[48, 49],
         [50, 51],
         [52, 53]],

        [[54, 55],
         [56, 57],
         [58, 59]]]])

In [64]:
y = y.flatten() # to convert any multi-dimensional array into a 1d array

In [65]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [66]:
y.mean() # mean of the array y

29.5

In [67]:
np.mean(y)

29.5

In [68]:
y.std() # stanndard deviation of the array y

17.318102282486574

In [69]:
y.var() # variance of the array y

299.9166666666667

In [92]:
s = np.arange(1,11).reshape(2,5)
s

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [93]:
s.mean(axis = 0) # axis = 0 means rows

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [94]:
s.mean(axis = 1) # axis = 1 means columns

array([3., 8.])

In [95]:
s.std(axis = 0)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [96]:
np.log(s) # log of the numppy array s

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [97]:
np.sin(s) # sin function

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [98]:
np.cos(s) # cos function

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153]])

In [99]:
np.tan(s) # tan function

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083]])

In [100]:
np.radians(180) # radians of a number

3.141592653589793

In [101]:
np.degrees(3.141592653589793) # radians to degrees

180.0

In [108]:
np.log10(s) # log fn

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ]])

In [141]:
n = np.arange(1,11)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
np.random.rand(10,10) # random fn

array([[1.07282063e-01, 9.62011962e-01, 6.02179440e-01, 1.93933813e-01,
        5.25114213e-01, 3.15404406e-01, 6.86514697e-01, 5.82445496e-01,
        4.78307308e-01, 5.41603580e-01],
       [2.89940332e-01, 9.56284801e-01, 9.30259669e-01, 7.71975734e-01,
        9.23502267e-02, 7.41812186e-01, 8.22707334e-01, 2.63387514e-01,
        6.97591757e-02, 4.91797612e-01],
       [7.17357697e-02, 8.63695390e-01, 5.74827590e-01, 2.60805133e-01,
        3.08981969e-01, 5.77871059e-01, 7.80205160e-01, 9.57212080e-01,
        5.45553663e-01, 7.67449434e-01],
       [7.44079630e-01, 7.99639580e-01, 4.91942470e-01, 6.37353433e-01,
        9.23829622e-01, 3.27061825e-01, 9.56440095e-01, 7.69312492e-01,
        4.50044194e-02, 9.34321846e-01],
       [2.20138460e-01, 5.17551557e-01, 7.62436029e-02, 3.43213188e-04,
        5.30386778e-01, 3.41743185e-01, 1.49925365e-01, 8.97864061e-01,
        4.89527766e-02, 7.29126481e-01],
       [7.77539651e-01, 5.44149883e-01, 6.96469911e-01, 7.69480757e-01,
   

In [143]:
np.random.randint(10,50,(10,10)) # randint fn

array([[34, 32, 38, 40, 39, 24, 23, 31, 13, 15],
       [30, 23, 38, 21, 27, 16, 11, 27, 28, 30],
       [37, 26, 26, 30, 40, 49, 38, 31, 37, 39],
       [17, 36, 24, 18, 16, 28, 34, 28, 12, 28],
       [21, 20, 38, 41, 29, 12, 20, 27, 12, 35],
       [43, 36, 19, 35, 29, 22, 43, 11, 49, 44],
       [19, 34, 35, 33, 43, 37, 32, 40, 44, 39],
       [31, 45, 47, 11, 31, 24, 42, 49, 26, 40],
       [48, 11, 34, 37, 22, 42, 25, 49, 25, 21],
       [11, 45, 20, 28, 14, 23, 45, 40, 39, 26]])

In [153]:
np.random.shuffle(n) # shuffles the numpy array
n

array([ 2,  7,  8,  5,  9,  3, 10,  4,  1,  6])

In [154]:
n.argmax() # returns the index of the largest element

6

In [155]:
n.argmin() # returns the index of the smallest element

8