In [1]:
#!pip install pandas
#!pip install numpy
import pandas as pd
import numpy as np

In [40]:
data = np.arange(30).reshape(6,5)

In [41]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [42]:
df = pd.DataFrame(data, columns = ["Jithesh", "B", "C", "D", "E"], index = ["x","y","z","p","q","r"])
df

Jithesh   B   C   D   E
x        0   1   2   3   4
y        5   6   7   8   9
z       10  11  12  13  14
p       15  16  17  18  19
q       20  21  22  23  24
r       25  26  27  28  29

In [43]:
df.columns

Index(['Jithesh', 'B', 'C', 'D', 'E'], dtype='object')

In [44]:
df.columns = ['A', 'B', 'C', 'D', 'E']
df

A   B   C   D   E
x   0   1   2   3   4
y   5   6   7   8   9
z  10  11  12  13  14
p  15  16  17  18  19
q  20  21  22  23  24
r  25  26  27  28  29

In [45]:
df.index

Index(['x', 'y', 'z', 'p', 'q', 'r'], dtype='object')

In [46]:
df.index = ['p','q','r','x','y','z']
df

A   B   C   D   E
p   0   1   2   3   4
q   5   6   7   8   9
r  10  11  12  13  14
x  15  16  17  18  19
y  20  21  22  23  24
z  25  26  27  28  29

In [47]:
type(df)

pandas.core.frame.DataFrame

In [48]:
d = {"AA":[1,2,3,4,5,6], "BB":[11,22,33,44,55,66], "CC":[101,102,103,104,105,106]}
df1 = pd.DataFrame(d)
df1

AA  BB   CC
0   1  11  101
1   2  22  102
2   3  33  103
3   4  44  104
4   5  55  105
5   6  66  106

In [49]:
d = {"AA":[1,2,3,4,5,], "BB":[11,22,33,44,55,66], "CC":[101,102,103,104,105,106]}
pd.DataFrame(d)

ValueError: All arrays must be of the same length

# getting and setting the values in the dataframe

In [ ]:
df["A"]

In [12]:
df1["AA"]

0    1
1    2
2    3
3    4
4    5
5    6
Name: AA, dtype: int64

In [13]:
df1.AA

0    1
1    2
2    3
3    4
4    5
5    6
Name: AA, dtype: int64

In [14]:
df.A

p     0
q     5
r    10
x    15
y    20
z    25
Name: A, dtype: int32

In [15]:
df.loc['p']

A    0
B    1
C    2
D    3
E    4
Name: p, dtype: int32

In [17]:
type(df.A)# pandas series 

pandas.core.series.Series

In [114]:
df

A   B   C   D   E
p   0   1   2   3   4
q   5   6   7   8   9
r  10  11  12  13  14
x  15  16  17  18  19
y  20  21  22  23  24
z  25  26  27  28  29

In [115]:
df.T #transpose- swaps rows and columns

p  q   r   x   y   z
A  0  5  10  15  20  25
B  1  6  11  16  21  26
C  2  7  12  17  22  27
D  3  8  13  18  23  28
E  4  9  14  19  24  29

In [37]:
df.iloc[0] #or df.loc['p']

A    0
B    1
C    2
D    3
E    4
Name: p, dtype: int32

In [117]:
df1.AA

0    1
1    2
2    3
3    4
4    5
5    6
Name: AA, dtype: int64

In [118]:
df1.AA = [2, 4, 6, 8, 10, 12]

In [119]:
df1

AA  BB   CC
0   2  11  101
1   4  22  102
2   6  33  103
3   8  44  104
4  10  55  105
5  12  66  106

In [120]:
df1.iloc[0] = [2, 22, 222]
df1

AA  BB   CC
0   2  22  222
1   4  22  102
2   6  33  103
3   8  44  104
4  10  55  105
5  12  66  106

In [39]:
df

A   B   C   D   E
p   0   1   2   3   4
q   5   6   7   8   9
r  10  11  12  13  14
x  15  16  17  18  19
y  20  21  22  23  24
z  25  26  27  28  29

In [122]:
df.D.y

23

In [123]:
df.D['y']

23

In [124]:
df['D']['y']

23

In [125]:
df['D'].y

23

In [41]:
df[['A','D','B']]

A   D   B
p   0   3   1
q   5   8   6
r  10  13  11
x  15  18  16
y  20  23  21
z  25  28  26

In [20]:
df[['A']] #DataFrame

A
p   0
q   5
r  10
x  15
y  20
z  25

In [21]:
df['A']# Series

p     0
q     5
r    10
x    15
y    20
z    25
Name: A, dtype: int32

In [129]:
np.array(df['A']) #1D array

array([ 0,  5, 10, 15, 20, 25])

In [130]:
np.array(df[['A']]) #2D array

array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25]])

In [46]:
z = np.arange(80).reshape(8,10)
df2 = pd.DataFrame(z, columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df2

A   B   C   D   E   F   G   H   I   J
a   0   1   2   3   4   5   6   7   8   9
b  10  11  12  13  14  15  16  17  18  19
c  20  21  22  23  24  25  26  27  28  29
d  30  31  32  33  34  35  36  37  38  39
e  40  41  42  43  44  45  46  47  48  49
f  50  51  52  53  54  55  56  57  58  59
g  60  61  62  63  64  65  66  67  68  69
h  70  71  72  73  74  75  76  77  78  79

In [48]:
np.array(df2[['A']])

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70]])

In [50]:
df

A   B   C   D   E
p   0   1   2   3   4
q   5   6   7   8   9
r  10  11  12  13  14
x  15  16  17  18  19
y  20  21  22  23  24
z  25  26  27  28  29

### Drop rows and columns 

In [54]:
df.drop('C', axis = 1, inplace = True) #inplace=True will allow you to make inplace changes(same as df=df.drop('C', axis=1)) 

In [55]:
df #axis=1 means columns

A   B   D   E
p   0   1   3   4
q   5   6   8   9
r  10  11  13  14
x  15  16  18  19
y  20  21  23  24
z  25  26  28  29

In [56]:
df.drop('q', axis = 0, inplace = True) #axis=0 means rows
df

A   B   D   E
p   0   1   3   4
r  10  11  13  14
x  15  16  18  19
y  20  21  23  24
z  25  26  28  29

In [57]:
df.reset_index()

index   A   B   D   E
0     p   0   1   3   4
1     r  10  11  13  14
2     x  15  16  18  19
3     y  20  21  23  24
4     z  25  26  28  29

In [58]:
df.reset_index(drop = True, inplace = True)# removes index
df

A   B   D   E
0   0   1   3   4
1  10  11  13  14
2  15  16  18  19
3  20  21  23  24
4  25  26  28  29

In [59]:
df.sort_index(ascending = False)

A   B   D   E
4  25  26  28  29
3  20  21  23  24
2  15  16  18  19
1  10  11  13  14
0   0   1   3   4

In [2]:
df.sort_values("E", ascending = True)

NameError: name 'df' is not defined

In [62]:
df

A   B   D   E
0   0   1   3   4
1  10  11  13  14
2  15  16  18  19
3  20  21  23  24
4  25  26  28  29

In [154]:
df.to_csv('abc.csv') #to save the created Data Frame as a csv file, there are various functions used to save it in different file formats